name: 'Camera Play '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26288
title: 'An experimental look at my photography '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#171400'
    - '#ff0000'
    - '#8f751b'
    - '#ffbeb9'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
