analytics: {}
color:
  brandColors:
    - '#E0D8C8'
    - '#586820'
    - '#807048'
    - '#A0C030'
    - '#D0C088'
  brandStrength: 0
  lightness: 0.6875
  rhythmicContrast: 0.25
  saturation: 0.5
cta: {}
layout_spectrum: 0.36374
name: 'Camera Play '
opengraph: {}
purpose: []
typography_spectrum: 0.602477
