analytics: {}
color:
  brandColors:
    - '#E0D8C8'
    - '#586820'
    - '#807048'
    - '#A0C030'
    - '#D0C088'
  brandStrength: 0.668918
  lightness: 0.5625
  rhythmicContrast: 1
  saturation: 0.625
cta: {}
layout_spectrum: 0.182432
name: 'Camera Play '
opengraph: {}
purpose: []
typography_spectrum: 0.602477
