name: 'Camera Play '
favicon: null
layout_spectrum: 0.36374
typography_spectrum: 0.602477
title: 'An experimental look at my photography '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0D8C8'
    - '#586820'
    - '#807048'
    - '#A0C030'
    - '#D0C088'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
