name: 'Camera Play '
favicon: null
layout_spectrum: 0.48961
typography_spectrum: 0.602477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0D8C8'
    - '#586820'
    - '#807048'
    - '#A0C030'
    - '#D0C088'
  brandStrength: 0
  lightness: 0.693693
  saturation: 0.972973
  rhythmicContrast: 0.225225
purpose: []
